services:
  postgres:
    image: postgres:latest
    container_name: expense-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: expense-tracker
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
    depends_on:
      - postgres

volumes:
  postgres_data:


